spring:
  application:
    name: User-Service
  config:
    import: configserver:http://localhost:8086
    
#circuitbreker config    
management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always
      
#resilience4j config
resilience4j:
  circuitbreaker:
    instances:
      departmentEmployeeBreaker:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 6s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED

# retry config        
  retry:
    instances:
     departmentEmployeeService:
      max-attempts: 3
      wait-duration: 5s
      
      
# rate limiter
  ratelimiter:
    instances:
     userRateLimiter:
       limit-refresh-period: 4s
       limit-for-period: 2
       timeout-duration: 0s
 
   
     
     
     
      
      