server:
  port: 8081
  
spring:
  application:
    name: API-GATEWAY
  config:
     import: configserver:http://localhost:8086
    
 
  cloud:
    gateway:
      routes:
      - id: USER-SERVICE 
        uri: lb://USER-SERVICE
        predicates:
         - Path=/users/**
         
      - id: EMPLOYEE-SERVICE 
        uri: lb://EMPLOYEE-SERVICE
        predicates:
         - Path=/employee/**
         
      - id: DEPARTMENT-SERVICE 
        uri: lb://DEPARTMENT-SERVICE
        predicates:
         - Path=/department/**
       
      
#eureka:
# instance:
#    prefer-ip-address: true
# client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#     defaultZone: http://localhost:8761/eureka    
    