server:
  port: 8086
spring:
  application:
    name: CONFIG-SERVER
    #this code is for getting configuration from github
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Uday-Shastrakar/microservice-config
          clone-on-start: true